# Generated by Django 5.1 on 2024-08-26 10:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company_users', '0002_rename_user_type_companyuser_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, default='Redesign all the web pages with animation.', max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project_images/')),
                ('assigneduser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_details', to='company_users.companyuser')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
