# Generated by Django 5.1 on 2024-08-29 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bugs', '0002_alter_bug_assigneduser'),
        ('company_users', '0003_rename_username_companyuser_name'),
        ('projects', '0004_rename_projectname_project_name_alter_project_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bug',
            old_name='bug_type',
            new_name='status',
        ),
        migrations.AlterField(
            model_name='bug',
            name='assignedproject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_bugs', to='projects.project'),
        ),
        migrations.AlterField(
            model_name='bug',
            name='assigneduser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_bugs', to='company_users.companyuser'),
        ),
    ]
