# Generated by Django 5.1 on 2024-08-26 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_rename_name_project_projectname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='assigneduser',
            new_name='manager',
        ),
    ]
