# Generated by Django 5.1 on 2024-08-29 08:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_users', '0002_rename_user_type_companyuser_type_and_more'),
        ('projects', '0003_rename_assigneduser_project_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='projectname',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='media/project_images/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='managed_user', to='company_users.companyuser'),
        ),
    ]
